### ISSUE TITLE
Add a method for retrieving global game/mission var

### ISSUE THREAD

**Issue by OrhanNasuf** [cleolibrary/CLEO-Redux#10]

**Comment by x87** [comment]
Using global variables in CLEO scripts is a bad practice and source of many issues. How can you guarantee correct results on a modified main.scm where global variables have different ids?

**Comment by OrhanNasuf** [comment]
> Using global variables in CLEO scripts is a bad practice and source of many issues. How can you guarantee correct results on a modified main.scm where global variables have different ids?

While I understand that dealing with global variables is a bad practice in any context, it is what Rockstar decided to do, and it is the only way to check whether a specific mission has been passed or not.

Some use cases include rewarding the player for passing a specific mission, activating a functionality only after a certain amount of progress or displaying achievements.

Based on your concern, I made a test with CLEO 2.0.0.6 on GTA 3:

```
{$CLEO .cs}
{$USE ini}

wait 500
write_int_to_ini_file $FLAG_JOEY_MISSION1_PASSED "CLEO\test.ini" "MISSIONS_PASSED" "JOEY_1" // Exists
write_int_to_ini_file $THIS_DOES_NOT_EXIST "CLEO\test.ini" "TEST_SECTION" "NOT_EXIST" // Does not exist
terminate_this_script
```

This was the result:

![test-write-gvar-to-ini](https://user-images.githubusercontent.com/40820079/143623055-1f465c1a-4903-424a-978f-4336d963c651.jpg)

So it seems that either 0 is returned when accessing a global var that doesn't exist, or IniFile.WriteInt() is doing some magic.
Either way it wouldn't cause a conflict with a modified main script if handled correctly.
Perhaps a function in CLEO-Redux could do something similar, but return undefined or -1 for non-existent vars.

I tried to work around this limit by writing the values to a .ini file with CLEO, which I was then going to access in my javascript with CLEO-Redux; but the File and ini plugins break when CLEO-Redux is loaded, and they cannot be used.
Is this a known issue?

**Comment by x87** [comment]
> File and ini plugins break when CLEO-Redux is loaded

those plugins will only work if original CLEO 2.0.0.6 is present in the same directory
https://github.com/cleolibrary/CLEO-Redux#running-cleo-redux-as-an-addon-to-cleo-library

> So it seems that either 0 is returned when accessing a global var that doesn't exist, or IniFile.WriteInt() is doing some magic.

most likely $THIS_DOES_NOT_EXIST was compiled to the first free id (one that is not declared in CustomVariables.ini) and all free variables gets initialized to 0 by the default.

 > Some use cases include rewarding the player for passing a specific mission, activating a feature only after a certain amount of progress or displaying achievements.

Right, also someone mentioned on Discord that usage of timer/counter opcodes require a global variable. I will look into what we can do here.

**Comment by OrhanNasuf** [comment]
> those plugins will only work if original CLEO 2.0.0.6 is present in the same directory https://github.com/cleolibrary/CLEO-Redux#running-cleo-redux-as-an-addon-to-cleo-library

Thank you!
The .cs script is now able to write the values without issue, but the game still crashes when attempting to read in javascript.

**Comment by x87** [comment]
Script that reads from and writes to the global SCM variable from JS code:
https://github.com/cleolibrary/CLEO-Redux/blob/master/examples/scm.js

Example script that displays ONMISSION variable on screen. To change the var value use `writeScmVariable(id, value)`

```js

import { readScmVariable, writeScmVariable } from "./cleo_plugins/scm";

// get variable offset for the current game
const ONMISSION_ID = getOnMissionId();

// display the variable value on screen
while (true) {
  wait(250);
  FxtStore.insert("scm_var", readScmVariable(ONMISSION_ID).toString());
  Text.PrintNow("scm_var", 500, 1);
}

// ONMISSION var has different id in each game
function getOnMissionId() {
  switch (GAME) {
    case "re3":
    case "gta3":
    case "gta3_unreal":
      return 207;
    case "reVC":
    case "vc":
    case "vc_unreal":
      return 313;
    case "sa":
    case "sa_unreal":
      return 409;
  }
  throw new Error("Unsupported game");
}
```

**Comment by x87** [comment]
ONMISSION = 0
![image](https://user-images.githubusercontent.com/5698288/159192185-b721aa89-a1ad-45aa-826f-8f2c83d6ef5f.png)

ONMISSION = 1
![image](https://user-images.githubusercontent.com/5698288/159192224-846fc84f-0779-4c21-a8d5-7650f14dfc9a.png)

**Comment by JuniorDjjr** [comment]
> Right, also someone mentioned on Discord that usage of timer/counter opcodes require a global variable. I will look into what we can do here.

In CLEO+ I created the opcodes for the local variable, it was pretty easy btw (internally, the game uses a pointer). I think this is important to add it natively in CLEO Redux.  
https://github.com/JuniorDjjr/CLEOPlus/blob/main/CLEOPlus/Timer.cpp

Global variables have always been bad practice, and now it's worse as a game patch can change their id (rare, but still), plus this problem that every game is an id, you have to search for ids etc. There are also more common cases, like using an available global variable, and in a patch it is no longer available, or another script uses too etc...


> Some use cases include rewarding the player for passing a specific mission, activating a feature only after a certain amount of progress or displaying achievements.

Remember that there are some stats that help with this, and it's a much better practice, some of them count how many missions of certain character has passed, or a certain mission has been completed, or how many cities have been unlocked etc. It doesn't solve all cases, but most of it (some more important).

**Comment by x87** [comment]
Available with [scm.ts](https://github.com/x87/scm.ts)
