### ISSUE TITLE
[IV] CLEO Redux does not work with FusionFix installed

### ISSUE THREAD

**Issue by ZH-Hristov** [cleolibrary/CLEO-Redux#108]
GTA IV refuses to launch when both CLEO Redux and FusionFix installed. I have tried with both the dinput8.dll provided by FusionFix and the one from the Ultimate ASI Loader repo.

The game outputs no errors and there are no errors in the CLEO log.

**Comment by ThirteenAG** [comment]
Recent fusion fix hooks two text functions for its gxt loader, maybe that's why?

**Comment by ZH-Hristov** [comment]
I'll try the previous version and report back.

**Comment by x87** [comment]
@ZH-Hristov with latest FusionFix, try renaming cleo_redux.asi to something like the_cleo_redux.asi. presumably it should make asi loader load CLEO after fusion fix and the order of setting conflicting hooks might be important here. Let us know if it solves the problem

**Comment by ZH-Hristov** [comment]
> @ZH-Hristov with latest FusionFix, try renaming cleo_redux.asi to something like the_cleo_redux.asi. presumably it should make asi loader load CLEO after fusion fix and the order of setting conflicting hooks might be important here. Let us know if it solves the problem

Just tried the_cleo_redux.asi and z_cleo_redux.asi. Sadly it didn't seem to change anything and the game closes itself again.

**Comment by ZH-Hristov** [comment]
Ah wait, sorry. I should have tried this before posting. It seems to work if I put the CLEO Redux asi in the plugins folder where fusion fix is and also rename it so that it's farther in the alphabetical order.

**Comment by x87** [comment]
Try to put both ASI in root folder (not plugins), and CLEO plugins in CLEO\cleo_plugins

**Comment by ZH-Hristov** [comment]
Game launched once, tried a script with text.PrintHelp which I assume is FXT/GXT related and the game crashed (script works on older version of FusionFix).

Now the game just doesn't launch like before.

**Comment by x87** [comment]
Ok, I suppose it should be fixed on FusionFix end

**Comment by ThirteenAG** [comment]
Should be fixed in [v3.0.8](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/releases/tag/v3.0.8) then.

**Comment by ZH-Hristov** [comment]
Yep, fixed now. Thanks!
