### ISSUE TITLE
[SA:DE] Fatal Error when using opcode 076c in a script

### ISSUE THREAD

**Issue by waluigiisbest99** [cleolibrary/CLEO-Redux#13]
Hi i tried to give the mafia territory around Las Venturas using the opcode 076c which would normally work perfectly fine in old San Andreas with CLEO 4 but with SA DE each time it refuses to load the game and causes a UE4 Fatal Error to occur?

**Comment by XMDS** [comment]
The first parameter of the 067C command is the key name of gxt, currently does not support fxt custom text, so you can only use the name that has been defined by the game gxt to use them

**Comment by waluigiisbest99** [comment]
> The first parameter of the 076C command is the key name of gxt, currently does not support fxt custom text, so you can only use the name that has been defined by the game gxt to use them

will that ever be supported?

**Comment by x87** [comment]
@waluigiisbest99 can you show the code?

**Comment by waluigiisbest99** [comment]
> @waluigiisbest99 can you show the code?

// This file was decompiled using SASCM.ini published by Seemann (http://sannybuilder.com/files/SASCM.rar) on 13.10.2007
{$CLEO .cs}

//-------------MAIN---------------
thread "ITALIAN_MAFIA" 

:ITALIAN_MAFIA_17
wait 0 
if 
   Player.Defined($PLAYER_CHAR)
else_jump @ITALIAN_MAFIA_17 
jump @ITALIAN_MAFIA_44 

:ITALIAN_MAFIA_44
0237: set_gang 5 weapons_to 0 22 24 
0237: set_gang 6 weapons_to 0 22 30
076C: set_zone 'STRIP1' gang 6 density_to 70 
076C: set_zone 'STRIP2' gang 6 density_to 80  // Strip Club
076C: set_zone 'STRIP3' gang 6 density_to 70 
076C: set_zone 'STRIP4' gang 6 density_to 80 
076C: set_zone 'ISLE' gang 6 density_to 80  // The Emerald Isle 
076C: set_zone 'OVS' gang 5 density_to 70  // Old Venturas Strip
076C: set_zone 'CALI1' gang 5 density_to 80 
076C: set_zone 'CALI2' gang 5 density_to 80 
076C: set_zone 'ROY' gang 5 density_to 70  // Royal Casino
076C: set_zone 'WWE' gang 5 density_to 70  // Whitewood Estates
076C: set_zone 'LOT' gang 5 density_to 70  // Come-A-Lot
076C: set_zone 'PRP1' gang 5 density_to 80 
076C: set_zone 'PRP3' gang 5 density_to 80 
076C: set_zone 'PRP4' gang 5 density_to 80 
076C: set_zone 'DRAG' gang 6 density_to 70  // The Four Dragons Casino
0A93: end_custom_thread

**Comment by x87** [comment]
@waluigiisbest99 opcode 0A93 is not supported in SA: DE. use only custom opcode listed here https://github.com/cleolibrary/CLEO-Redux#compatibility-with-the-trilogy-the-definitive-edition

**Comment by waluigiisbest99** [comment]
> @waluigiisbest99 opcode 0A93 is not supported in SA: DE. Only use custom opcodes listed here https://github.com/cleolibrary/CLEO-Redux#compatibility-with-the-trilogy-the-definitive-edition

Thanks i managed to finally get it work by changing it to this.

0000: NOP 
thread "ITALIAN_MAFIA"
:ITALIAN_MAFIA_17
wait 0
if
Player.Defined($PLAYER_CHAR)
else_jump @ITALIAN_MAFIA_17
jump @ITALIAN_MAFIA_44

:ITALIAN_MAFIA_44
0237: set_gang 5 weapons_to 0 22 24
0237: set_gang 6 weapons_to 0 22 30
076C: set_zone 'STRIP1' controlled_by_gang 6 density_to 70
076C: set_zone 'STRIP2' controlled_by_gang 6 density_to 80 
076C: set_zone 'STRIP3' controlled_by_gang 6 density_to 70
076C: set_zone 'STRIP4' controlled_by_gang 6 density_to 80
076C: set_zone 'ISLE' controlled_by_gang 6 density_to 80 
076C: set_zone 'OVS' controlled_by_gang 5 density_to 70 
076C: set_zone 'CALI1' controlled_by_gang 5 density_to 80
076C: set_zone 'CALI2' controlled_by_gang 5 density_to 80
076C: set_zone 'ROY' controlled_by_gang 5 density_to 70 
076C: set_zone 'WWE' controlled_by_gang 5 density_to 70 
076C: set_zone 'LOT' controlled_by_gang 5 density_to 70 
076C: set_zone 'PRP1' controlled_by_gang 5 density_to 80
076C: set_zone 'PRP3' controlled_by_gang 5 density_to 80
076C: set_zone 'PRP4' controlled_by_gang 5 density_to 80
076C: set_zone 'DRAG' controlled_by_gang 6 density_to 70
