### ISSUE TITLE
Error when using TypeScript

### ISSUE THREAD

**Issue by nonunknown** [cleolibrary/CLEO-Redux#20]
when you use typescript and put numbers this error shows:
![image](https://user-images.githubusercontent.com/58845030/144768915-ff3d6eb0-b53e-49f7-b09b-1e75e96e4a87.png)

the only way to solve it was doing this:

![image](https://user-images.githubusercontent.com/58845030/144768950-2154e46f-7d09-4f77-b328-6bb143e2ee6a.png)

**Comment by x87** [comment]
TypeScript has no support for nominal types (user-defined types extending base primitive types such as number) and without this hack it treats all arguments as having type `number` and not (`int` or `float`)
![ts-int](https://user-images.githubusercontent.com/5698288/144902406-3ba9ed5d-b85b-49e3-a20c-b3fd51c1cc4e.png) which is inconvenient for the end-user.

this is one of the most anticipated features in TS https://github.com/microsoft/TypeScript/issues/202

I would love to explore first-class support for TS in CLEO in the future. If, for time being, someone can provide a definition that would both:

1) make parameters display in autocomplete as either `int` or `float`
2) don't break TS compilation

I will happily update autogenerate .d.ts

**Comment by BountyBomj** [comment]
> TypeScript has no support for nominal types (user-defined types extending base primitive types such as number) and without this hack it treats all arguments as having type `number` and not (`int` or `float`) ![ts-int](https://user-images.githubusercontent.com/5698288/144902406-3ba9ed5d-b85b-49e3-a20c-b3fd51c1cc4e.png) which is inconvenient for the end-user.
> 
> this is one of the most anticipated features in TS [microsoft/TypeScript#202](https://github.com/microsoft/TypeScript/issues/202)
> 
> I would love to explore first-class support for TS in CLEO in the future. If, for time being, someone can provide a definition that would both:
> 
> 1. make parameters display in autocomplete as either `int` or `float`
> 2. don't break TS compilation
> 
> I will happily update autogenerate .d.ts

I replaced int with int | number and float with float | number, maybe this? 
https://github.com/BountyBomj/a/blob/main/index.d.ts

**Comment by x87** [comment]
looks like 

```ts
/** Integer value */
type int = number & { _int: never } | number;
/** Floating-point value */
type float = number & { _float: never } | number;
```

does the trick. VS Code shows params as `int` or `float` yet `number` type is perfectly assignable

**Comment by x87** [comment]
1.0.5 supports typescript
