### ISSUE TITLE
SA: DE How to read and write memory

### ISSUE THREAD

**Issue by GouLiGuoJiaNaive** [cleolibrary/CLEO-Redux#25]
Is there a feasible way to read/write the memory of San Andreas (The Definitive Edition)
I can easily modify them through the Cheat engine, but I need to use this opcodes in the script to achieve some functions.

**Comment by XMDS** [comment]
Currently, the read and write memory commands cannot be used in the DE version of SA.  Because the game uses x64.  These commands will be supported in future versions, please wait.  But you can implement them through C++ and write your project (if you need)

**Comment by GouLiGuoJiaNaive** [comment]
It seems to be waiting for a while, but I believe it will not be too long.

**Comment by XMDS** [comment]
In fact, a few hours ago.  x87 is discussing commands to read and write memory.  But only for discussion, because the game uses x64, the memory method will be different.  The order hasn't been confirmed yet

**Comment by XMDS** [comment]
In addition, there is no need for two Chinese to communicate here in English.  You can contact me with QQ

**Comment by JuniorDjjr** [comment]
I do not have so much knowledge in memory hacking, but I didn't understand the difficulty for being x64.

Soon in the early days I made a test asi to understand how the memory of the game is positioned and if it is possible to write it without any problems (SA:DE), and I actually wrote new values in memory, and I saw it by the cheat engine, the values really have been changed correctly and have effect in the game. But I didn't do anything so complex, probably I'm missing some detail here.

I used https://github.com/thelink2012/Injector

**Comment by XMDS** [comment]
> I do not have so much knowledge in memory hacking, but I didn't understand the difficulty for being x64.
> 
> Soon in the early days I made a test asi to understand how the memory of the game is positioned and if it is possible to write it without any problems (SA:DE), and I actually wrote new values in memory, and I saw it by the cheat engine, the values really have been changed correctly and have effect in the game. But I didn't do anything so complex, probably I'm missing some detail here.
> 
> I used https://github.com/thelink2012/Injector

Yes.  What you said is absolutely correct.  I did exactly this in my "DisableTextMissing.asi", it prevents the text "missing" from being left behind.  I used 
https://github.com/thelink2012/injector.git

In addition, I recommend adding this:
https://github.com/ThirteenAG/Hooking.Patterns.git

**Comment by x87** [comment]
0.8.4 adds READ_MEMORY and WRITE_MEMORY in SA:DE
https://github.com/cleolibrary/CLEO-Redux/blob/master/using-memory-64.md
