### ISSUE TITLE
log says "This version of CLEO Redux does not support custom opcodes in main.scm in San Andreas: The Definitive Edition"

### ISSUE THREAD

**Issue by l0ck3rd0p3** [cleolibrary/CLEO-Redux#26]
I have the latest version of the trilogy but the latest version of cleo just isn't working for me and when i check the cleo logs it says "This version of CLEO Redux does not support custom opcodes in main.scm in San Andreas: The Definitive Edition" i used the day one patch of the trilogy and it works but when i updated it, it stops working for me. Any solutions?

**Comment by x87** [comment]
check https://github.com/cleolibrary/CLEO-Redux/blob/master/TROUBLESHOOTING.md

that line only means that you can't use custom opcodes in the main.scm file. Only in separate CS/JS scripts

**Comment by l0ck3rd0p3** [comment]
But I'm not using custom opcodes? and where is the main.scm file? oh and btw im using a cracked version, but i dont know if that has anything to do with it.

**Comment by x87** [comment]
you should be specific on what you mean "cleo just isn't working". Provide a full log file and not just one line that is expected to be there.

**Comment by l0ck3rd0p3** [comment]
the cs and js files i have used to work before i updated the game to the latest version, but it's oka. I deleted everything and i'm gonna try to reinstall the game because I feel like the repack i installed had some corrupted files.

**Comment by l0ck3rd0p3** [comment]
I don't know what I'm doing wrong man, cleo scripts still aren't working. And here's the full log file;

13:44:43 [INFO] CLEO Redux 0.8.3 (x64)
13:44:43 [INFO] Copyright (c) 2021, Seemann. Available under the license agreement at https://re.cleo.li/LICENSE.txt
13:44:43 [INFO] Visit re.cleo.li for news and updates.
13:44:43 [INFO] Host identified as San Andreas: The Definitive Edition (1.0.0.14718)
13:44:43 [INFO] CleoConfig { log_opcodes: false, allow_cs: true, allow_js: true, check_updates: true, permission_level: Lax }
13:44:43 [INFO] Registering custom commands
13:44:43 [INFO] Registering command 0C00 IS_KEY_PRESSED
13:44:43 [INFO] Registering command 0C01 INT_ADD
13:44:43 [INFO] Registering command 0C02 INT_SUB
13:44:43 [INFO] Registering command 0C03 INT_MUL
13:44:43 [INFO] Registering command 0C04 INT_DIV
13:44:43 [INFO] Registering command 0C05 TERMINATE_THIS_CUSTOM_SCRIPT
13:44:43 [WARN] This version of CLEO Redux does not support custom opcodes in main.scm in San Andreas: The Definitive Edition
13:45:12 [INFO] New event received: "init scripts"
13:45:12 [INFO] Started scanning the CLEO directory

**Comment by x87** [comment]
Read installation instructions carefully https://github.com/cleolibrary/CLEO-Redux#installation

Scripts folder should not be used for CLEO

**Comment by l0ck3rd0p3** [comment]
ohhh okay my bad, since the cleo file has .asi i thought it's supposed to be there. Thanks!
