### ISSUE TITLE
Require external libraries

### ISSUE THREAD

**Issue by borsuczyna** [cleolibrary/CLEO-Redux#27]
Really hope for requiring external libraries for example WebSocket for pseudo-multiplayer

```js
const WebSocket = require('ws')

**Comment by borsuczyna** [comment]
Since I know it's not using Node.js, maybe external libraries to load functions from another .dll/.asi file?

**Comment by x87** [comment]
support for loading functions from external libraries is planned, much like CLEO 4 does it

https://library.sannybuilder.com/#/sa/classes/DynamicLibrary

**Comment by x87** [comment]
it loads any dll file and returns its handle, think of it as WinAPI's `LoadLibrary()` function

**Comment by x87** [comment]
Loading dll files and calling functions is supported with Dylib.cleo plugin (available to download here: https://github.com/cleolibrary/CLEO-Redux/releases)
