### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by TheArtemMaps** [cleolibrary/CLEO-Redux#29]
hi, how do you make asi and compile it?

**Comment by x87** [comment]
It's just a renamed dll file.

**Comment by TheArtemMaps** [comment]
> It's just a renamed dll file.

i know, but how you make these?

**Comment by x87** [comment]
it depends on the language and tools that you use. for example with C++ and MSVS
https://docs.microsoft.com/ru-ru/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=msvc-170

you can find similar guides for other languages

**Comment by TheArtemMaps** [comment]
do you have any contacts?
