### ISSUE TITLE
How do I add CLEO to Grand Theft Auto RE: 3?

### ISSUE THREAD

**Issue by CipherHYT** [cleolibrary/CLEO-Redux#33]
I've been trying to add a cleo mod to RE3, but the mod won't load. Does anyone know how to? Thanks.

**Comment by x87** [comment]
show cleo_redux.log

**Comment by CipherHYT** [comment]
```
20:56:54 [INFO] CLEO Redux 0.8.6 (x86)
20:56:54 [INFO] Copyright (c) 2021-2022, Seemann. Available under the license agreement at https://re.cleo.li/LICENSE.txt
20:56:54 [INFO] Visit re.cleo.li for news and updates.
20:56:54 [INFO] Host identified as GTA III (1.0)
20:56:54 [INFO] Image base address 0xec0000
20:56:54 [INFO] CleoConfig { log_opcodes: false, allow_cs: true, allow_js: true, check_updates: true, allow_fxt: true, permission_level: Lax }
20:56:54 [INFO] Found another instance of CLEO. Compiled scripts support is delegated.
20:56:54 [INFO] Registering custom commands
20:56:54 [INFO] Registering unsafe command 0A8C WRITE_MEMORY with required permission mem
20:56:54 [INFO] Registering unsafe command 0A8D READ_MEMORY with required permission mem
20:56:54 [INFO] Registering unsafe command 0AA5 CALL_FUNCTION with required permission mem
20:56:54 [INFO] Registering unsafe command 0AA6 CALL_METHOD with required permission mem
20:56:54 [INFO] Registering unsafe command 0AA7 CALL_FUNCTION_RETURN with required permission mem
20:56:54 [INFO] Registering unsafe command 0AA8 CALL_METHOD_RETURN with required permission mem
20:56:54 [INFO] Registering command 0AB0 IS_KEY_PRESSED
20:56:54 [INFO] Registering command 0A8E INT_ADD
20:56:54 [INFO] Registering command 0A8F INT_SUB
20:56:54 [INFO] Registering command 0A90 INT_MUL
20:56:54 [INFO] Registering command 0A91 INT_DIV
20:56:54 [INFO] Registering command 0002 GOTO
20:56:54 [INFO] Registering command 004C GOTO_IF_TRUE
20:56:54 [INFO] Registering command 004D GOTO_IF_FALSE
20:56:54 [INFO] Registering command 0050 GOSUB
20:56:54 [INFO] Registering command 0A93 TERMINATE_THIS_CUSTOM_SCRIPT
20:56:54 [INFO] Found FXT dictionary CLEO\CLEO_TEXT\Weapshop.fxt
20:56:54 [INFO] FXT files successfully loaded
```

**Comment by x87** [comment]
>Found another instance of CLEO. Compiled scripts support is delegated.

it means your cs script is loaded and run by CLEO for GTA 3, not CLEO Redux. In delegate mode CLEO Redux only runs JS scripts.
https://github.com/cleolibrary/CLEO-Redux#running-cleo-redux-as-an-addon-to-cleo-library

**Comment by CipherHYT** [comment]
well, how do i load cleo redux?
@x87

**Comment by x87** [comment]
what is your goal? Do you develop a mod or just want to run some script?

**Comment by CipherHYT** [comment]
To run some scripts.
@x87

**Comment by x87** [comment]
I can't help you if you don't provide more information. Just "the mod won't load" is not helpful. Describe what mod, how you did you install it, show screenshots of an error or any details of your attempts to run it.

**Comment by CipherHYT** [comment]
Ok, So I installed two scripts, the MapV2 script, and the vc like weapon shop. After adding the ASI and the ASI loader, I opened the game, nothing loaded. The Cleo version didn't pop up (2.0.0.6), so I thought I needed Cleo Redux. When I booted up with redux, I saw the version on the bottom right corner, started a new game. And I drove to Ammu-Nation, showed the old ammunation, then I pressed tab on my keyboard, nothing popped up. Is that enough information or do you need more @x87?
I will try to send screenshots if needed.

**Comment by x87** [comment]
https://github.com/cleolibrary/CLEO-Redux#compatibility-with-re3-and-revc

run re3.exe
