### ISSUE TITLE
Add Android support

### ISSUE THREAD

**Issue by MatiDragon-YT** [cleolibrary/CLEO-Redux#35]

**Comment by XMDS** [comment]
Is there any news about the GTA DE mobile platform release？

Also, I'd love to see some features of Cleo Redux supported in the mobile version of the classic trilogy.  But I think Android CLEO and x87 are not the same project.  Unless @x87 intends to make Redux for Android.

**Comment by MatiDragon-YT** [comment]
> Is there any news about the GTA DE mobile platform release?

**New** as such? no.
Just what R* said, at the beginning..
That it will come out between January and June 2022.

---

> Also, I'd love to see some features of Cleo Redux supported in the mobile version of the classic trilogy. **But I think Android CLEO and x87 are not the same project.** Unless x87 intends to make Redux for Android.

I think the same as you. But if CLEO Redux managed to enter the Definitive Edition of PC, why not to Android in the not too distant future?

**Comment by MatiDragon-YT** [comment]
@XMDS 
> Is there any news about the GTA DE mobile platform release?

**New** as such? no.
Just what R* said, at the beginning..
That it will come out between January and June 2022.

---

> Also, I'd love to see some features of Cleo Redux supported in the mobile version of the classic trilogy. **But I think Android CLEO and x87 are not the same project.** Unless x87 intends to make Redux for Android.

I think the same as you. But if CLEO Redux managed to enter the Definitive Edition of PC, why not to Android in the not too distant future?

**Comment by XMDS** [comment]
> 
> I think the same as you. But if CLEO Redux managed to enter the Definitive Edition of PC, why not to Android in the not too distant future?

I think AlexB, the author of the Android CLEO library, will support CLEO for the DE version of GTA for mobile platforms (provided that Rockstar releases the DE mobile version)
As said above. Redux and the Android CLEO library are two projects. I think it's unlikely that Redux will support Android.

**Comment by MatiDragon-YT** [comment]
Could a small modified APK be made from scratch to at least read vanilla opcodes?

**Comment by XMDS** [comment]
@MatiDragon-YT  
If you want, I can send you an apk with CLEO library installed and support cleo, but only if you tell me your phone system (for example, what is the Android system?)

**Comment by x87** [comment]
not is scope
