### ISSUE TITLE
[GTASA Classic] How to disable watermark?

### ISSUE THREAD

**Issue by niresh1234** [cleolibrary/CLEO-Redux#39]
![Screenshot (239)](https://user-images.githubusercontent.com/98110551/160430734-efeb0b17-7149-42f1-bf37-33d0acf3bd81.png)

**Comment by x87** [comment]
@niresh1234 update to 0.9.4, there is a new config option `DisplayMenuInfo`. Set it to 0.

https://re.cleo.li/docs/en/config.html
