### ISSUE TITLE
CLEO Redux doesn't work on re3

### ISSUE THREAD

**Issue by dacbe0701** [cleolibrary/CLEO-Redux#4]
When i run re3, CLEO Redux simply does not want to see the game and does not work. Even if the file "re3.pdb" is present, the script loader still does not see the game

**Comment by x87** [comment]
Which version of re3 are you using? CLEO Redux only supports "Windows D3D9 MSS 32bit" version.

Can you provide the cleo.log file?

**Comment by dacbe0701** [comment]
Windows D3D9 OAL 64bit, i don't have cleo.log as the reason is above
