### ISSUE TITLE
cleo_redux.asi does not work on Windows 7

### ISSUE THREAD

**Issue by TheArtemMaps** [cleolibrary/CLEO-Redux#5]
how to solve it?

**Comment by x87** [comment]
screenshot? logs? information about the game?

**Comment by TheArtemMaps** [comment]
> screenshot? logs? information about the game?

yeah, sorry. gta sa 1.0 
![image](https://user-images.githubusercontent.com/91487356/140990861-9acfe855-5279-4deb-8d54-1cbe7a1f671b.png)
![image](https://user-images.githubusercontent.com/91487356/140990894-d9fc60f0-c9fb-4af4-b7bd-9af2605424d3.png)
idk what log i need to past. cleo.log or modloader.log?

**Comment by x87** [comment]
What Windows is it?

**Comment by TheArtemMaps** [comment]
> What Windows is it?

windows 7

**Comment by x87** [comment]
I see. CLEO Redux uses [GetSystemTimePreciseAsFileTime](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemtimepreciseasfiletime) that is only available on Windows 8+.

I will look into removing this dependency but it's a low priority for me now. Sorry.

**Comment by TheArtemMaps** [comment]
> I see. CLEO Redux uses [GetSystemTimePreciseAsFileTime](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemtimepreciseasfiletime) that is only available on Windows 8+.
> 
> I will look into removing this dependency but it's a low priority for me now. Sorry.

ok

**Comment by D3Pheonix** [comment]
Need a guide of using dynamicLibrary.load()

**Comment by x87** [comment]
@D3Pheonix hi. which part is confusing?

**Comment by D3Pheonix** [comment]
> @D3Pheonix hi. which part is confusing?
I can easily get sampStructure by this cleo code
[code]0AA2: 0@ = load_library "SAMP.DLL"
000A: 0@ += 0x21A0F8 // samp info offset
0A8D: 0@ = read_memory 0@ size 4 virtual_protect TRUE //  0@ - samp structure[/code]

so, on js it's like:
[code]var library = DynamicLibrary.Load("samp.dll");
sampStructure()

function sampStructure(lib) {
    lib += 0x21A0F8;
    var stSamp = Memory.Read(lib, true); // crash

[/code]

**Comment by x87** [comment]
> var stSamp = Memory.Read(lib, 4, true); //  **Causes game crash** WHY ?!?!

What CLEO Redux version are you using? There was an issue with Memore.Read (see #6) that is fixed in 0.7.4. You can also enable opcode log in the config (see 
https://github.com/cleolibrary/CLEO-Redux#scm-log) that should help to find a possible cause of the crash.

> var libKernel = DynamicLibrary.Load("kernel32.dll");
> var localTimeAddress = DynamicLibrary.GetProcedure("GetLocalTime", libKernel); 
  // TypeError: undefined not callable (property 'GetProcedure' of [object Function])
  // WHY UNDEFINED ?!?!
 
Commands having `self` argument are called as methods on a class instance. They also start with a lowercase letter (constructors and static methods start with a capital letter).

In your case the correct form should be `libKernel.getProcedure("GetLocalTime"); `

There is however an issue, as CLEO 4 has unconventionally put `self` as the second argument in 0AA4 (https://library.sannybuilder.com/#/sa/CLEO/0AA4), so CLEO Redux may call this instruction with incorrect parameter order. I will take a look.

**Comment by D3Pheonix** [comment]
> > var stSamp = Memory.Read(lib, 4, true); //  **Causes game crash** WHY ?!?!
> 
> What CLEO Redux version are you using? There was an issue with Memory.Read (see #6) that is fixed in 0.7.4. You can also enable opcode log in the config (see https://github.com/cleolibrary/CLEO-Redux#scm-log) that should help to find a possible cause of the crash.
> 
> > var libKernel = DynamicLibrary.Load("kernel32.dll");
> > var localTimeAddress = DynamicLibrary.GetProcedure("GetLocalTime", libKernel);
> > // TypeError: undefined not callable (property 'GetProcedure' of [object Function])
> > // WHY UNDEFINED ?!?!
> 
> Commands having `self` argument are called as methods on a class instance. They also start with a lowercase letter (constructors and static methods start with a capital letter).
> 
> In your case the correct form should be `libKernel.getProcedure("GetLocalTime"); `
> 
> There is however an issue, as CLEO 4 has unconventionally put `self` as the second argument in 0AA4 (https://library.sannybuilder.com/#/sa/CLEO/0AA4), so CLEO Redux may call this instruction with incorrect parameter order. I will take a look.

Я обновил до 0.7.4 и заработало). Имею в виду первый пример с samp.dll
А вот со вторым нужно разбираться.
Про .getProcedure я вот не знал, т.к. на вики с большой написано
```DynamicLibrary.GetProcedure(procName: string, self: DynamicLibrary, var address: int): bool```

**Comment by x87** [comment]
@D3Pheonix please open a new discussion here https://github.com/cleolibrary/CLEO-Redux/discussions

I don't want to use this ticket for multiple questions. also please prefer English as it might help other people to understand the problem and use provided solutions

**Comment by x87** [comment]
> 
> 
> I see. CLEO Redux uses [GetSystemTimePreciseAsFileTime](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemtimepreciseasfiletime) that is only available on Windows 8+.
> 
> I will look into removing this dependency but it's a low priority for me now. Sorry.

@TheArtemMaps please try new version 0.7.6

**Comment by TheArtemMaps** [comment]
> > I see. CLEO Redux uses [GetSystemTimePreciseAsFileTime](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemtimepreciseasfiletime) that is only available on Windows 8+.
> > I will look into removing this dependency but it's a low priority for me now. Sorry.
> 
> @TheArtemMaps please try new version 0.7.6

yes works now. thanks, and sorry for my long reply. also how does hot reload works? i tried to add/change scripts, but nothing changed.

**Comment by x87** [comment]
> i tried to add/change scripts, but nothing changed.

what is in your cleo_redux.log?

**Comment by TheArtemMaps** [comment]
22:05:34 [INFO] CLEO Redux 0.8.0 (x86)
22:05:34 [INFO] Copyright (c) 2021, Seemann. Available under the license agreement at https://re.cleo.li/LICENSE.txt
22:05:34 [INFO] Visit re.cleo.li for news and updates.
22:05:34 [INFO] Host identified as San Andreas (1.0)
22:05:34 [INFO] CleoConfig { log_opcodes: false, allow_cs: true, allow_js: true, check_updates: true, permission_level: Lax }
22:05:34 [INFO] Found another instance of CLEO. Compiled scripts support is delegated.
22:05:34 [INFO] Registering custom commands
22:05:34 [INFO] Registering unsafe command 0A8C WRITE_MEMORY with required permission mem
22:05:34 [INFO] Registering unsafe command 0A8D READ_MEMORY with required permission mem
22:05:34 [INFO] Registering unsafe command 0AA5 CALL_FUNCTION with required permission mem
22:05:34 [INFO] Registering unsafe command 0AA6 CALL_METHOD with required permission mem
22:05:34 [INFO] Registering unsafe command 0AA7 CALL_FUNCTION_RETURN with required permission mem
22:05:34 [INFO] Registering unsafe command 0AA8 CALL_METHOD_RETURN with required permission mem
22:05:34 [INFO] Registering command 0AB0 IS_KEY_PRESSED
22:05:34 [INFO] Registering command 0A8E INT_ADD
22:05:34 [INFO] Registering command 0A8F INT_SUB
22:05:34 [INFO] Registering command 0A90 INT_MUL
22:05:34 [INFO] Registering command 0A91 INT_DIV
22:05:34 [INFO] Registering command 0A93 TERMINATE_THIS_CUSTOM_SCRIPT
22:05:52 [INFO] New event received: "init scripts"
22:05:52 [INFO] Started scanning the CLEO directory
22:05:52 [INFO] Skipped CS script CLEO\2 HYDRAS_PATROL.cs
22:05:52 [INFO] Skipped CS script CLEO\24-7 SHop.cs
22:05:52 [INFO] Skipped CS script CLEO\AI - AT400 Contrail.cs
22:05:52 [INFO] Skipped CS script CLEO\AI - Andromeda Contrail.cs
22:05:52 [INFO] Skipped CS script CLEO\AI - Shamal Contrail.cs
22:05:52 [INFO] Skipped CS script CLEO\AI Hydra Contrail.cs
22:05:52 [INFO] Skipped CS script CLEO\AT400 Contraill.cs
22:05:52 [INFO] Skipped CS script CLEO\Adrenaline by TrushinVlad 2.cs
22:05:52 [INFO] Skipped CS script CLEO\Airplane Crash.cs
22:05:52 [INFO] Skipped CS script CLEO\Airplane Tire Skid (Junior_Djjr).cs
22:05:52 [INFO] Skipped CS script CLEO\Al_Planes_1.1.cs
22:05:52 [INFO] Skipped CS script CLEO\Andromeda Contrail.cs
22:05:52 [INFO] Skipped CS script CLEO\Anim4.cs
22:05:52 [INFO] Skipped CS script CLEO\AnimModByxXx2o1o.cs
22:05:52 [INFO] Skipped CS script CLEO\BADABING.cs
22:05:52 [INFO] Skipped CS script CLEO\Beachball.cs
22:05:52 [INFO] Skipped CS script CLEO\Birds.cs
22:05:52 [INFO] Skipped CS script CLEO\Bochka.cs
22:05:52 [INFO] Skipped CS script CLEO\BulletView.cs
22:05:52 [INFO] Skipped CS script CLEO\Bus With Passengers.cs
22:05:52 [INFO] Skipped CS script CLEO\Buy Property (Junior_Djjr).cs
22:05:52 [INFO] Skipped CS script CLEO\Buy Property - save pickup system.cs
22:05:52 [INFO] Skipped CS script CLEO\Car lensfares.cs
22:05:52 [INFO] Skipped CS script CLEO\Car lights.cs
22:05:52 [INFO] Skipped CS script CLEO\Car_Ghost.cs
22:05:52 [INFO] Skipped CS script CLEO\Chainsaw smoke.cs
22:05:52 [INFO] Skipped CS script CLEO\Cops reaction.cs
22:05:52 [INFO] Skipped CS script CLEO\Cops(Newswan).cs
22:05:52 [INFO] Skipped CS script CLEO\CopsDriveBy.cs
22:05:52 [INFO] Skipped CS script CLEO\Cult.cs
22:05:52 [INFO] Skipped CS script CLEO\Dance.cs
22:05:52 [INFO] Skipped CS script CLEO\Desert.cs
22:05:52 [INFO] Skipped CS script CLEO\Diesel v2.cs
22:05:52 [INFO] Skipped CS script CLEO\Dinamite.cs
22:05:52 [INFO] Skipped CS script CLEO\Distribution v0.5.cs
22:05:52 [INFO] Skipped CS script CLEO\Dodo with ad banner 2 - копия (2).cs
22:05:52 [INFO] Skipped CS script CLEO\Dodo with ad banner 2 - копия (3).cs
22:05:52 [INFO] Skipped CS script CLEO\Dodo with ad banner 2 - копия (4).cs
22:05:52 [INFO] Skipped CS script CLEO\Dodo with ad banner 2 - копия (5).cs
22:05:52 [INFO] Skipped CS script CLEO\Dodo with ad banner 2 - копия.cs
22:05:52 [INFO] Skipped CS script CLEO\Dodo with ad banner 2.cs
22:05:52 [INFO] Skipped CS script CLEO\Drivethru.cs
22:05:52 [INFO] Skipped CS script CLEO\FPScounter.cs
22:05:52 [INFO] Skipped CS script CLEO\Fail mission taxi.cs
22:05:52 [INFO] Skipped CS script CLEO\Fair Police (Junior_Djjr).cs
22:05:52 [INFO] Skipped CS script CLEO\Fall Bike Ped Reaction (Junior_Djjr).cs
22:05:52 [INFO] Skipped CS script CLEO\Fire_Vision.cs
22:05:52 [INFO] Skipped CS script CLEO\Food, fire, etc.cs
22:05:52 [INFO] Skipped CS script CLEO\Gang Ride For Adapted Vehicles.cs
22:05:52 [INFO] Skipped CS script CLEO\Ghost ships - копия (2).cs
22:05:52 [INFO] Skipped CS script CLEO\Ghost ships - копия (3).cs
22:05:52 [INFO] Skipped CS script CLEO\Ghost ships - копия.cs
22:05:52 [INFO] Skipped CS script CLEO\Ghost ships.cs
22:05:52 [INFO] Skipped CS script CLEO\Grove Gang Missions Season 1 - 5 Missions.cs
22:05:52 [INFO] Skipped CS script CLEO\HCLovehate.cs
22:05:52 [INFO] Skipped CS script CLEO\HCmeleehomies.cs
22:05:52 [INFO] Skipped CS script CLEO\HCstayincar.cs
22:05:52 [INFO] Skipped CS script CLEO\HOME_BRAINS.cs
22:05:52 [INFO] Skipped CS script CLEO\HP pickups by TrushinVlad.cs
22:05:52 [INFO] Skipped CS script CLEO\HYDRA_PLACE.cs
22:05:52 [INFO] Skipped CS script CLEO\Handshake (Junior_Djjr).cs
22:05:52 [INFO] Skipped CS script CLEO\Handshake P2 (Junior_Djjr).cs
22:05:52 [INFO] Skipped CS script CLEO\Healt.cs
22:05:52 [INFO] Skipped CS script CLEO\HeightLimit.cs
22:05:52 [INFO] Skipped CS script CLEO\Heli in the sky.cs
22:05:52 [INFO] Skipped CS script CLEO\HeliVerMotor.cs
22:05:52 [INFO] Skipped CS script CLEO\Home Protection v1.cs
22:05:52 [INFO] Skipped CS script CLEO\Homeless and Trash Bags (Junior_Djjr).cs
22:05:52 [INFO] Skipped CS script CLEO\Horns Divert (Junior_Djjr).cs
22:05:52 [INFO] Skipped CS script CLEO\House light like GTA VC.cs
22:05:52 [INFO] Skipped CS script CLEO\Hydra Contrail.cs
22:05:52 [INFO] Skipped CS script CLEO\Inciedents on the road.cs
22:05:52 [INFO] Skipped CS script CLEO\Kolonka.cs
22:05:52 [INFO] Skipped CS script CLEO\LS-Graveyard-Fix.cs
22:05:52 [INFO] Skipped CS script CLEO\Leaf1.cs
22:05:52 [INFO] Skipped CS script CLEO\Leaf2.cs
22:05:52 [INFO] Skipped CS script CLEO\Leaf3.cs
22:05:52 [INFO] Skipped CS script CLEO\Leaf4.cs
22:05:52 [INFO] Skipped CS script CLEO\Leaf5.cs
22:05:52 [INFO] Skipped CS script CLEO\Lighted barriers.cs
22:05:52 [INFO] Skipped CS script CLEO\Lighthouse & Pyramid Fix (Junior_Djjr).cs
22:05:52 [INFO] Skipped CS script CLEO\Live CJ v6.cs
22:05:52 [INFO] Skipped CS script CLEO\MDPM (Junior_Djjr).cs
22:05:52 [INFO] Skipped CS script CLEO\MDPM - AI.cs
22:05:52 [INFO] Skipped CS script CLEO\MDPM - NPCs.cs
22:05:52 [INFO] Skipped CS script CLEO\MDPM - Root.cs
22:05:52 [INFO] Skipped CS script CLEO\MDPM - Speaker.cs
22:05:52 [INFO] Skipped CS script CLEO\MDPM - Tutorial.cs
22:05:52 [INFO] Skipped CS script CLEO\Meteoro.cs
22:05:52 [INFO] Skipped CS script CLEO\Mines.cs
22:05:52 [INFO] Skipped CS script CLEO\Mini  mapping.cs
22:05:52 [INFO] Skipped CS script CLEO\Mod_Meteoros.cs
22:05:52 [INFO] Skipped CS script CLEO\Mount to Helicopter.cs
22:05:52 [INFO] Skipped CS script CLEO\Mr Whoopie with siren.cs
22:05:52 [INFO] Skipped CS script CLEO\NPC Helmet Mod v2.5 - CJ Helmet.cs
22:05:52 [INFO] Skipped CS script CLEO\NPC Helmet Mod v2.5 by -Lukass B-.cs
22:05:52 [INFO] Skipped CS script CLEO\Newspaper1.cs
22:05:52 [INFO] Skipped CS script CLEO\Newspaper10.cs
22:05:52 [INFO] Skipped CS script CLEO\Newspaper11.cs
22:05:52 [INFO] Skipped CS script CLEO\Newspaper12.cs
22:05:52 [INFO] Skipped CS script CLEO\Newspaper13.cs
22:05:52 [INFO] Skipped CS script CLEO\Newspaper14.cs
22:05:52 [INFO] Skipped CS script CLEO\Newspaper15.cs
22:05:52 [INFO] Skipped CS script CLEO\Newspaper2.cs
22:05:52 [INFO] Skipped CS script CLEO\Newspaper3.cs
22:05:52 [INFO] Skipped CS script CLEO\Newspaper4.cs
22:05:52 [INFO] Skipped CS script CLEO\Newspaper5.cs
22:05:52 [INFO] Skipped CS script CLEO\Newspaper6.cs
22:05:52 [INFO] Skipped CS script CLEO\Newspaper7.cs
22:05:52 [INFO] Skipped CS script CLEO\Newspaper8.cs
22:05:52 [INFO] Skipped CS script CLEO\Newspaper9.cs
22:05:52 [INFO] Skipped CS script CLEO\Night.cs
22:05:52 [INFO] Skipped CS script CLEO\No Clip (Junior_Djjr).cs
22:05:52 [INFO] Skipped CS script CLEO\Not_Fire_Vision.cs
22:05:52 [INFO] Skipped CS script CLEO\Odometr.cs
22:05:52 [INFO] Skipped CS script CLEO\Oldair.cs
22:05:52 [INFO] Skipped CS script CLEO\PISS.cs
22:05:52 [INFO] Skipped CS script CLEO\Palm1.cs
22:05:52 [INFO] Skipped CS script CLEO\Palm2.cs
22:05:52 [INFO] Skipped CS script CLEO\Palm3.cs
22:05:52 [INFO] Skipped CS script CLEO\Palm4.cs
22:05:52 [INFO] Skipped CS script CLEO\Palm5.cs
22:05:52 [INFO] Skipped CS script CLEO\Palm6.cs
22:05:52 [INFO] Skipped CS script CLEO\Palm7.cs
22:05:52 [INFO] Skipped CS script CLEO\Paratroopers_swat.cs
22:05:52 [INFO] Skipped CS script CLEO\Paul.Maccer.Rosenberg.cs
22:05:52 [INFO] Skipped CS script CLEO\Peds Buy Food (Junior_Djjr).cs
22:05:52 [INFO] Skipped CS script CLEO\Peds' reaction on car explodes v2.cs
22:05:52 [INFO] Skipped CS script CLEO\Peds' reaction on cars.cs
22:05:52 [INFO] Skipped CS script CLEO\Peds' reaction on hits.cs
22:05:52 [INFO] Skipped CS script CLEO\Phoenix's working airscoop by TrushinVlad.cs
22:05:52 [INFO] Skipped CS script CLEO\Pilot_job.cs
22:05:52 [INFO] Skipped CS script CLEO\Police maverick coronas.cs
22:05:52 [INFO] Skipped CS script CLEO\Policiais atirando de helicopteros.cs
22:05:52 [INFO] Skipped CS script CLEO\Press_Car.cs
22:05:52 [INFO] Skipped CS script CLEO\Put Glasses (Junior_Djjr).cs
22:05:52 [INFO] Skipped CS script CLEO\RCHeli.cs
22:05:52 [INFO] Skipped CS script CLEO\RagDoll_FrameAdjust.cs
22:05:52 [INFO] Skipped CS script CLEO\RagDoll_uniqueAbility.cs
22:05:52 [INFO] Skipped CS script CLEO\Ragdoll Missions Fix (Junior_Djjr).cs
22:05:52 [INFO] Skipped CS script CLEO\Raio (Amilton e Twister).cs
22:05:52 [INFO] Skipped CS script CLEO\Rampages - PART 1.cs
22:05:52 [INFO] Skipped CS script CLEO\Rampages - PART 2.cs
22:05:52 [INFO] Skipped CS script CLEO\Rampages - PART 3.cs
22:05:52 [INFO] Skipped CS script CLEO\Rampages - PART 4.cs
22:05:52 [INFO] Skipped CS script CLEO\Rampages - PART 5.cs
22:05:52 [INFO] Skipped CS script CLEO\Rampages - PART 6.cs
22:05:52 [INFO] Skipped CS script CLEO\Real Liberty City.cs
22:05:52 [INFO] Skipped CS script CLEO\Reverse lights by TrushinVlad.cs
22:05:52 [INFO] Skipped CS script CLEO\Rolling-field (Tumbleweed) v5.2.cs
22:05:52 [INFO] Skipped CS script CLEO\SMCA01.cs
22:05:52 [INFO] Skipped CS script CLEO\SMCA02.cs
22:05:52 [INFO] Skipped CS script CLEO\SMCA03.cs
22:05:52 [INFO] Skipped CS script CLEO\SMCA04.cs
22:05:52 [INFO] Skipped CS script CLEO\SMCA05.cs
22:05:52 [INFO] Skipped CS script CLEO\SMCA06.cs
22:05:52 [INFO] Skipped CS script CLEO\SMCA07.cs
22:05:52 [INFO] Skipped CS script CLEO\SMCA08.cs
22:05:52 [INFO] Skipped CS script CLEO\SMCA09.cs
22:05:52 [INFO] Skipped CS script CLEO\SMCA10.cs
22:05:52 [INFO] Skipped CS script CLEO\SMOKINGs.cs
22:05:52 [INFO] Skipped CS script CLEO\Save.cs
22:05:52 [INFO] Skipped CS script CLEO\Screen.cs
22:05:52 [INFO] Skipped CS script CLEO\Shamal Contraill.cs
22:05:52 [INFO] Skipped CS script CLEO\Signaling.cs
22:05:52 [INFO] Skipped CS script CLEO\Siren lensflares.cs
22:05:52 [INFO] Skipped CS script CLEO\SlowMotion.cs
22:05:52 [INFO] Skipped CS script CLEO\Smoking-smoking_V2.0.cs
22:05:52 [INFO] Skipped CS script CLEO\Smoking[7].cs
22:05:52 [INFO] Skipped CS script CLEO\SpeedHack.cs
22:05:52 [INFO] Skipped CS script CLEO\Start.cs
22:05:52 [INFO] Skipped CS script CLEO\Starter[0][1][0].cs
22:05:52 [INFO] Skipped CS script CLEO\StrongPeds.cs
22:05:52 [INFO] Skipped CS script CLEO\Taxi light fix.cs
22:05:52 [INFO] Skipped CS script CLEO\Termal.cs
22:05:52 [INFO] Skipped CS script CLEO\Termometr.cs
22:05:52 [INFO] Skipped CS script CLEO\The Ballas Revenge On Sweet - Cleo Mission.cs
22:05:52 [INFO] Skipped CS script CLEO\Thiefs.cs
22:05:52 [INFO] Skipped CS script CLEO\Timer.cs
22:05:52 [INFO] Skipped CS script CLEO\Truck sounds 2.cs
22:05:52 [INFO] Skipped CS script CLEO\VC Airport Security.cs
22:05:52 [INFO] Skipped CS script CLEO\VCJumpCamera.cs
22:05:52 [INFO] Skipped CS script CLEO\VCS v3.0.cs
22:05:52 [INFO] Skipped CS script CLEO\Vehicles_generate.cs
22:05:52 [INFO] Skipped CS script CLEO\Vikin.cs
22:05:52 [INFO] Skipped CS script CLEO\WALK_DRUNK.cs
22:05:52 [INFO] Skipped CS script CLEO\WUZIBET.cs
22:05:52 [INFO] Skipped CS script CLEO\WangCarsPeds.cs
22:05:52 [INFO] Skipped CS script CLEO\Water effects.cs
22:05:52 [INFO] Skipped CS script CLEO\WaterEffect.cs
22:05:52 [INFO] Skipped CS script CLEO\WaterSM_Bomb.cs
22:05:52 [INFO] Skipped CS script CLEO\WaterSM_By_Air.cs
22:05:52 [INFO] Skipped CS script CLEO\WaterSM_Head.cs
22:05:52 [INFO] Skipped CS script CLEO\WaterSM_Solder.cs
22:05:52 [INFO] Skipped CS script CLEO\WreckBalling.cs
22:05:52 [INFO] Skipped CS script CLEO\Zombie.cs
22:05:52 [INFO] Skipped CS script CLEO\airports.cs
22:05:52 [INFO] Skipped CS script CLEO\airstrike.cs
22:05:52 [INFO] Skipped CS script CLEO\amazingscreen.cs
22:05:52 [INFO] Skipped CS script CLEO\anim.cs
22:05:52 [INFO] Skipped CS script CLEO\anim2.cs
22:05:52 [INFO] Skipped CS script CLEO\anim228.cs
22:05:52 [INFO] Skipped CS script CLEO\ballas-raid-gs.cs
22:05:52 [INFO] Skipped CS script CLEO\barracks passenger.cs
22:05:52 [INFO] Skipped CS script CLEO\bashka.cs
22:05:52 [INFO] Skipped CS script CLEO\basketball_court.cs
22:05:52 [INFO] Skipped CS script CLEO\battle royal.cs
22:05:52 [INFO] Skipped CS script CLEO\bortcomp.cs
22:05:52 [INFO] Skipped CS script CLEO\bum.cs
22:05:52 [INFO] Skipped CS script CLEO\camera.cs
22:05:52 [INFO] Skipped CS script CLEO\car accident.cs
22:05:52 [INFO] Skipped CS script CLEO\car_cop.cs
22:05:52 [INFO] Skipped CS script CLEO\carrec.cs
22:05:52 [INFO] Skipped CS script CLEO\catal.cs
22:05:52 [INFO] Skipped CS script CLEO\cheats.cs
22:05:52 [INFO] Skipped CS script CLEO\cmenu.cs
22:05:52 [INFO] Skipped CS script CLEO\cops.cs
22:05:52 [INFO] Skipped CS script CLEO\crspeed.cs
22:05:52 [INFO] Skipped CS script CLEO\dress2kickass.cs
22:05:52 [INFO] Skipped CS script CLEO\enterplaneC.S..cs
22:05:52 [INFO] Skipped CS script CLEO\enterplaneC.S.[passenger].cs
22:05:52 [INFO] Skipped CS script CLEO\entrada.cs
22:05:52 [INFO] Skipped CS script CLEO\epsilonism.cs
22:05:52 [INFO] Skipped CS script CLEO\file.cs
22:05:52 [INFO] Skipped CS script CLEO\fixers.cs
22:05:52 [INFO] Skipped CS script CLEO\fixers_markers.cs
22:05:52 [INFO] Skipped CS script CLEO\fixers_near.cs
22:05:52 [INFO] Skipped CS script CLEO\fixwheelturnback.cs
22:05:52 [INFO] Skipped CS script CLEO\flycarpet.cs
22:05:52 [INFO] Skipped CS script CLEO\food1.cs
22:05:52 [INFO] Skipped CS script CLEO\food2.cs
22:05:52 [INFO] Skipped CS script CLEO\food3.cs
22:05:52 [INFO] Skipped CS script CLEO\gates.cs
22:05:52 [INFO] Skipped CS script CLEO\great_gulyanka.cs
22:05:52 [INFO] Skipped CS script CLEO\greenwood.cs
22:05:52 [INFO] Skipped CS script CLEO\group_drive.cs
22:05:52 [INFO] Skipped CS script CLEO\gunner.cs
22:05:52 [INFO] Skipped CS script CLEO\helicover.cs
22:05:52 [INFO] Skipped CS script CLEO\helidriver.cs
22:05:52 [INFO] Skipped CS script CLEO\heligrab.cs
22:05:52 [INFO] Skipped CS script CLEO\hidden totem package pickup.cs
22:05:52 [INFO] Skipped CS script CLEO\homiesinside.cs
22:05:52 [INFO] Skipped CS script CLEO\katana_stealth_kill.cs
22:05:52 [INFO] Skipped CS script CLEO\kur.cs
22:05:52 [INFO] Skipped CS script CLEO\lab.cs
22:05:52 [INFO] Skipped CS script CLEO\limit.cs
22:05:52 [INFO] Skipped CS script CLEO\mspark.cs
22:05:52 [INFO] Skipped CS script CLEO\nitro.cs
22:05:52 [INFO] Skipped CS script CLEO\noshot.cs
22:05:52 [INFO] Skipped CS script CLEO\nuclear.cs
22:05:52 [INFO] Skipped CS script CLEO\on_off_engine.cs
22:05:52 [INFO] Skipped CS script CLEO\opendoor.cs
22:05:52 [INFO] Skipped CS script CLEO\parachute.cs
22:05:52 [INFO] Skipped CS script CLEO\parachuts.cs
22:05:52 [INFO] Skipped CS script CLEO\petrol.cs
22:05:52 [INFO] Skipped CS script CLEO\phoneservice.cs
22:05:52 [INFO] Skipped CS script CLEO\plane_crash.cs
22:05:52 [INFO] Skipped CS script CLEO\plane_starter.cs
22:05:52 [INFO] Skipped CS script CLEO\polmav.cs
22:05:52 [INFO] Skipped CS script CLEO\railwaysounds.cs
22:05:52 [INFO] Skipped CS script CLEO\random_actor_in_PLAYER_GROUP_3.0.cs
22:05:52 [INFO] Skipped CS script CLEO\razgovor2.cs
22:05:52 [INFO] Skipped CS script CLEO\record_player.cs
22:05:52 [INFO] Skipped CS script CLEO\rich_presence.cs
22:05:52 [INFO] Skipped CS script CLEO\riot_smoke01.cs
22:05:52 [INFO] Skipped CS script CLEO\riot_smoke02.cs
22:05:52 [INFO] Skipped CS script CLEO\rrrplayer.cs
22:05:52 [INFO] Skipped CS script CLEO\salida.cs
22:05:52 [INFO] Skipped CS script CLEO\sda.cs
22:05:52 [INFO] Skipped CS script CLEO\smokes.cs
22:05:52 [INFO] Skipped CS script CLEO\sterring_plg.cs
22:05:52 [INFO] Skipped CS script CLEO\street.cs
22:05:52 [INFO] Skipped CS script CLEO\sweets.cs
22:05:52 [INFO] Found JS script CLEO\test.js
22:05:52 [INFO] Successfully loaded CLEO\test.js and created a JS script with the name "test"
22:05:52 [INFO] Skipped CS script CLEO\trafic.cs
22:05:52 [INFO] Skipped CS script CLEO\traincamfix.cs
22:05:52 [INFO] Skipped CS script CLEO\u.s.m.c. desant.cs
22:05:52 [INFO] Skipped CS script CLEO\viatura estacionada by-pabblo 1.cs
22:05:52 [INFO] Skipped CS script CLEO\viatura estacionada by-pabblo 2.cs
22:05:52 [INFO] Skipped CS script CLEO\viatura estacionada by-pabblo 3.cs
22:05:52 [INFO] Skipped CS script CLEO\walk like a gang.cs
22:05:52 [INFO] Skipped CS script CLEO\zombie_headcrab[2].cs
22:05:52 [INFO] Skipped CS script CLEO\zombie_headcrab[3].cs
22:05:52 [INFO] Skipped CS script CLEO\zombie_headcrab[4].cs
22:05:52 [INFO] Skipped CS script CLEO\Вертолёт.cs
22:05:52 [INFO] Skipped CS script CLEO\Воздушная Лестница.cs
22:05:52 [INFO] Skipped CS script CLEO\Десант.cs
22:05:52 [INFO] Skipped CS script CLEO\Прыжок.cs
22:05:52 [INFO] Skipped CS script CLEO\Система вооружения полицейских.cs
22:05:52 [INFO] Skipped CS script CLEO\Система вооружения полицейских_2.cs
22:05:52 [INFO] Skipped CS script CLEO\Система вооружения полицейских_3.cs
22:05:52 [INFO] Skipped CS script CLEO\Система вооружения полицейских_4.cs
22:05:52 [INFO] Skipped CS script CLEO\городские_службы.cs
22:05:52 [INFO] Skipped CS script CLEO\разборки v.3 Финал.cs
22:05:52 [INFO] Skipped CS script CLEO\статуэтки.cs
22:05:52 [INFO] Skipped CS script CLEO\ученые.cs
22:05:52 [INFO] Script CLEO\test.js has been disposed
22:06:02 [INFO] Successfully loaded CLEO\test.js and created a JS script with the name "test"
22:06:02 [INFO] Script CLEO\test.js has been disposed

**Comment by x87** [comment]
which one of these you were trying to change?

**Comment by TheArtemMaps** [comment]
> which one of these you were trying to change?

this one SlowMotion.cs

**Comment by x87** [comment]
>22:05:34 [INFO] Found another instance of CLEO. Compiled scripts support is delegated.
>22:05:52 [INFO] Skipped CS script CLEO\SlowMotion.cs

hot reload does not work for CS scripts when there is another CLEO. only for JS scripts.

**Comment by TheArtemMaps** [comment]
but when i'm deleting cleo.asi and leaving cleo redux, game not launching getting error gta_sa.exe cannot be runned without cleo.asi. try reinstall programm

**Comment by x87** [comment]
CLEO Redux only works with CLEO 4 in San Andreas 1.0. So you don't have hot reload for CS scripts in this game
