### ISSUE TITLE
IntOperations.cleo

### ISSUE THREAD

**Issue by ghost** [cleolibrary/CLEO-Redux#66]
please make **IntOperations.cleo** plugin for cleo redux

**Comment by x87** [comment]
Why? JavaScript already has those operations

**Comment by niresh1234** [comment]
because, scripts which design for cleo4 are not working, when only installed cleo redux

**Comment by niresh1234** [comment]
as well as please add full cleo 4 support in cleo redux

**Comment by x87** [comment]
> because, scripts which design for cleo4 (which used IntOperations.cleo) are not working, when only installed cleo redux

why don't you install CLEO 4 to get those commands? CLEO 4 and CLEO Redux can coexist (in San Andreas).

**Comment by niresh1234** [comment]
but, why you not include all function of **[CLEO4](https://github.com/cleolibrary/CLEO4)** function into **[Cleo Redux](https://github.com/cleolibrary/CLEO-Redux)**
