### ISSUE TITLE
Does not work with reVC

### ISSUE THREAD

**Issue by RyanGlade** [cleolibrary/CLEO-Redux#71]
Will not load with reVC
I'll provide the log file if it helps:
15:18:14 [INFO] CLEO Redux 1.0.2 (x64)
15:18:14 [INFO] Copyright (c) 2021-2022, Seemann. Available under the license agreement at https://re.cleo.li/LICENSE.txt
15:18:14 [INFO] Visit re.cleo.li for news and updates.
15:18:15 [INFO] Host identified as reVC (64 bit)
15:18:15 [INFO] Image base address 0x7ff663ab0000
15:18:15 [WARN] CLEO Redux does not support CS scripts in reVC (64 bit)
15:18:15 [INFO] Registering custom commands
15:18:15 [INFO] Registering command IS_KEY_PRESSED
15:18:15 [INFO] Registering unsafe command READ_MEMORY with required permission mem
15:18:15 [INFO] Registering unsafe command WRITE_MEMORY with required permission mem
15:18:15 [INFO] Registering unsafe command CALL_FUNCTION with required permission mem
15:18:15 [INFO] SDK version 5
15:18:15 [INFO] Loading plugins from E:\GTA\GTAVC\CLEO\CLEO_PLUGINS
15:18:15 [INFO] Found plugin dylib64.cleo
15:18:15 [INFO] Dylib plugin 1.1
15:18:15 [INFO] Registering unsafe command LOAD_DYNAMIC_LIBRARY with required permission dll
15:18:15 [INFO] Registering unsafe command FREE_DYNAMIC_LIBRARY with required permission dll
15:18:15 [INFO] Registering unsafe command GET_DYNAMIC_LIBRARY_PROCEDURE with required permission dll
15:18:15 [INFO] Loaded plugin dylib64.cleo
15:18:15 [INFO] Found plugin IdeLoader64.cleo
15:18:15 [INFO] IDE Loader 1.1
15:18:15 [INFO] Registering a custom loader for glob "*.ide"
15:18:15 [INFO] Loaded plugin IdeLoader64.cleo
15:18:15 [INFO] Found plugin ImGuiReduxWin64.cleo
15:18:16 [INFO] Registering command IMGUI_BEGIN_FRAME
15:18:16 [INFO] Registering command IMGUI_END_FRAME
15:18:16 [INFO] Registering command IMGUI_BEGIN
15:18:16 [INFO] Registering command IMGUI_END
15:18:16 [INFO] Registering command IMGUI_SET_WINDOW_POS
15:18:16 [INFO] Registering command IMGUI_SET_WINDOW_SIZE
15:18:16 [INFO] Registering command IMGUI_SET_NEXT_WINDOW_POS
15:18:16 [INFO] Registering command IMGUI_SET_NEXT_WINDOW_SIZE
15:18:16 [INFO] Registering command IMGUI_DUMMY
15:18:16 [INFO] Registering command IMGUI_TEXT
15:18:16 [INFO] Registering command IMGUI_TEXT_CENTERED
15:18:16 [INFO] Registering command IMGUI_TEXT_DISABLED
15:18:16 [INFO] Registering command IMGUI_TEXT_WRAPPED
15:18:16 [INFO] Registering command IMGUI_TEXT_COLORED
15:18:16 [INFO] Registering command IMGUI_BULLET_TEXT
15:18:16 [INFO] Registering command IMGUI_SET_TOOLTIP
15:18:16 [INFO] Registering command IMGUI_BUTTON
15:18:16 [INFO] Registering command IMGUI_IMAGE_BUTTON
15:18:16 [INFO] Registering command IMGUI_INVISIBLE_BUTTON
15:18:16 [INFO] Registering command IMGUI_COLOR_BUTTON
15:18:16 [INFO] Registering command IMGUI_ARROW_BUTTON
15:18:16 [INFO] Registering command IMGUI_CHECKBOX
15:18:16 [INFO] Registering command IMGUI_SAMELINE
15:18:16 [INFO] Registering command IMGUI_NEWLINE
15:18:16 [INFO] Registering command IMGUI_COLUMNS
15:18:16 [INFO] Registering command IMGUI_NEXT_COLUMN
15:18:16 [INFO] Registering command IMGUI_SPACING
15:18:16 [INFO] Registering command IMGUI_SEPARATOR
15:18:16 [INFO] Registering command GET_FRAMERATE
15:18:16 [INFO] Registering command IMGUI_GET_VERSION
15:18:16 [INFO] Registering command IMGUI_GET_PLUGIN_VERSION
15:18:16 [INFO] Registering command IMGUI_SET_CURSOR_VISIBLE
15:18:16 [INFO] Registering command IMGUI_GET_FRAME_HEIGHT
15:18:16 [INFO] Registering command IMGUI_GET_WINDOW_POS
15:18:16 [INFO] Registering command IMGUI_GET_WINDOW_SIZE
15:18:16 [INFO] Registering command IMGUI_CALC_TEXT_SIZE
15:18:16 [INFO] Registering command IMGUI_GET_WINDOW_CONTENT_REGION_WIDTH
15:18:16 [INFO] Registering command IMGUI_BEGIN_MAINMENUBAR
15:18:16 [INFO] Registering command IMGUI_END_MAINMENUBAR
15:18:16 [INFO] Registering command IMGUI_MENU_ITEM
15:18:16 [INFO] Registering command IMGUI_SELECTABLE
15:18:16 [INFO] Registering command IMGUI_BEGIN_CHILD
15:18:16 [INFO] Registering command IMGUI_END_CHILD
15:18:16 [INFO] Registering command IMGUI_PUSH_ITEM_WIDTH
15:18:16 [INFO] Registering command IMGUI_POP_ITEM_WIDTH
15:18:16 [INFO] Registering command IMGUI_COLLAPSING_HEADER
15:18:16 [INFO] Registering command IMGUI_SLIDER_INT
15:18:16 [INFO] Registering command IMGUI_SLIDER_FLOAT
15:18:16 [INFO] Registering command IMGUI_INPUT_INT
15:18:16 [INFO] Registering command IMGUI_INPUT_FLOAT
15:18:16 [INFO] Registering command IMGUI_INPUT_TEXT
15:18:16 [INFO] Registering command IMGUI_RADIO_BUTTON
15:18:16 [INFO] Registering command IMGUI_COLOR_PICKER
15:18:16 [INFO] Registering command IMGUI_IS_ITEM_ACTIVE
15:18:16 [INFO] Registering command IMGUI_IS_ITEM_CLICKED
15:18:16 [INFO] Registering command IMGUI_IS_ITEM_FOCUSED
15:18:16 [INFO] Registering command IMGUI_IS_ITEM_HOVERED
15:18:16 [INFO] Registering command IMGUI_GET_SCALING_SIZE
15:18:16 [INFO] Registering command IMGUI_GET_DISPLAY_SIZE
15:18:16 [INFO] Registering command IMGUI_SET_NEXT_WINDOW_TRANSPARENCY
15:18:16 [INFO] Registering command IMGUI_SET_MESSAGE
15:18:16 [INFO] Registering command IMGUI_BULLET
15:18:16 [INFO] Registering command IMGUI_COMBO
15:18:16 [INFO] Registering command IMGUI_LOAD_IMAGE
15:18:16 [INFO] Registering command IMGUI_FREE_IMAGE
15:18:16 [INFO] Registering command IMGUI_PUSH_STYLE_VAR
15:18:16 [INFO] Registering command IMGUI_PUSH_STYLE_VAR2
15:18:16 [INFO] Registering command IMGUI_PUSH_STYLE_COLOR
15:18:16 [INFO] Registering command IMGUI_POP_STYLE_VAR
15:18:16 [INFO] Registering command IMGUI_POP_STYLE_COLOR
15:18:16 [INFO] Registering command IMGUI_TABS
15:18:16 [INFO] Loaded plugin ImGuiReduxWin64.cleo
15:18:16 [INFO] Found plugin IniFiles64.cleo
15:18:16 [INFO] IniFiles plugin 1.2
15:18:16 [INFO] Registering unsafe command READ_INT_FROM_INI_FILE with required permission fs
15:18:16 [INFO] Registering unsafe command WRITE_INT_TO_INI_FILE with required permission fs
15:18:16 [INFO] Registering unsafe command READ_FLOAT_FROM_INI_FILE with required permission fs
15:18:16 [INFO] Registering unsafe command WRITE_FLOAT_TO_INI_FILE with required permission fs
15:18:16 [INFO] Registering unsafe command READ_STRING_FROM_INI_FILE with required permission fs
15:18:16 [INFO] Registering unsafe command WRITE_STRING_TO_INI_FILE with required permission fs
15:18:16 [INFO] Loaded plugin IniFiles64.cleo
15:18:16 [INFO] Found plugin Input64.cleo
15:18:16 [INFO] Input plugin 1.3
15:18:16 [INFO] Registering command IS_KEY_PRESSED
15:18:16 [INFO] Registering command IS_KEY_DOWN
15:18:16 [INFO] Registering command IS_KEY_UP
15:18:16 [INFO] Registering command GET_LAST_KEY
15:18:16 [INFO] Registering command TEST_CHEAT
15:18:16 [INFO] Registering command HOLD_KEY
15:18:16 [INFO] Registering command RELEASE_KEY
15:18:16 [INFO] Registering command SET_CURSOR_POS
15:18:16 [INFO] Registering command GET_CURSOR_POS
15:18:16 [INFO] Loaded plugin Input64.cleo
15:18:16 [INFO] Found plugin MemoryOperations64.cleo
15:18:16 [INFO] Init MemoryOperations
15:18:16 [INFO] Registering unsafe command GET_IMAGE_BASE with required permission mem
15:18:16 [INFO] Registering unsafe command FIND_PATTERN with required permission mem
15:18:16 [INFO] Registering unsafe command ALLOC_NEAR with required permission mem
15:18:16 [INFO] Registering unsafe command READ_RELATIVE_OFFSET with required permission mem
15:18:16 [INFO] Registering unsafe command WRITE_RELATIVE_OFFSET with required permission mem
15:18:16 [INFO] Loaded plugin MemoryOperations64.cleo
15:18:16 [INFO] Found plugin TextLoader64.cleo
15:18:16 [INFO] TXT Loader 1.0
15:18:16 [INFO] Registering a custom loader for glob "*.txt"
15:18:16 [INFO] Registering a custom loader for glob "*.text"
15:18:16 [INFO] Loaded plugin TextLoader64.cleo
15:18:16 [INFO] API version 0.242
15:18:16 [INFO] Found FXT dictionary E:\GTA\GTAVC\CLEO\CLEO_TEXT\Clothes.fxt
15:18:16 [INFO] FXT files successfully loaded
15:18:16 [WARN] This version of CLEO Redux does not support custom opcodes in main.scm in reVC
15:18:31 [INFO] New event received: "init runtime"
15:18:31 [INFO] Started scanning the CLEO directory at E:\GTA\GTAVC\CLEO
15:18:31 [INFO] Skipped CS script E:\GTA\GTAVC\CLEO\d_chuvst.cs
15:18:31 [INFO] Skipped CS script E:\GTA\GTAVC\CLEO\d_GoodGangs.cs
15:18:31 [INFO] Skipped CS script E:\GTA\GTAVC\CLEO\d_moneyHUD.cs
15:18:31 [INFO] Skipped CS script E:\GTA\GTAVC\CLEO\d_PoliceFix.cs
15:18:31 [INFO] Skipped CS script E:\GTA\GTAVC\CLEO\d_PS2pickup.cs
15:18:31 [INFO] Skipped CS script E:\GTA\GTAVC\CLEO\d_sandcastle.cs
15:18:31 [INFO] Skipped CS script E:\GTA\GTAVC\CLEO\d_weap_fix.cs
15:18:31 [INFO] Skipped CS script E:\GTA\GTAVC\CLEO\Mix Sets.cs
15:18:31 [INFO] Skipped CS script E:\GTA\GTAVC\CLEO\VC.Walk.cs
15:18:31 [INFO] Skipped CS script E:\GTA\GTAVC\CLEO\vcpd_ps2_teargas.cs
15:18:31 [INFO] Skipped CS script E:\GTA\GTAVC\CLEO\WardrobeMod.cs
15:18:44 [INFO] New event received: "host shut down"
15:18:44 [INFO] Exit

**Comment by x87** [comment]
> 15:18:15 [WARN] CLEO Redux does not support CS scripts in reVC (64 bit)

I

**Comment by RyanGlade** [comment]
> > 15:18:15 [WARN] CLEO Redux does not support CS scripts in reVC (64 bit)
> 
> JS scripts only

Then how will I run cleo scripts with reVC?

**Comment by x87** [comment]
use 32-bit version of reVC
