### ISSUE TITLE
Problem: Silent Patch Installed in Modloader

### ISSUE THREAD

**Issue by 1234nir** [cleolibrary/CLEO-Redux#81]
When I installed Silent Patch in Modloader Folder

This window coms sometime (and sometime not)

Game works normally, but many times I start **gta_sa.exe** this window come

![Screenshot (252) - Copy](https://user-images.githubusercontent.com/120308983/208585630-a988f602-8373-4101-8e4f-c6247c5f2c62.png)

**Solution:** I think this plugin [(ImGuiRedux)](https://github.com/user-grinch/ImGuiRedux) try to find SilentPatch Files in GTA SA/VC/III root Direcory..
You can make an code

> if Silent Patch files not available in root Directory
> Then Try to Find Scripts Directory
> if not available in Scripts directory
> Then Try to Find Modloader Directory (with any subfolder)

**Comment by x87** [comment]
@user-grinch

**Comment by user-grinch** [comment]
@1234nir Does this fix your issue? Place it inside `CLEO/CLEO_PLUGINS`.
[ImGuiReduxWin32.zip](https://github.com/cleolibrary/CLEO-Redux/files/10270833/ImGuiReduxWin32.zip)

**Comment by 1234nir** [comment]
Problem are still there (using recently provided plugin file by @user-grinch )

![Screenshot (254)](https://user-images.githubusercontent.com/120308983/208825372-8a103891-38f8-4826-bfcc-7ea77371d795.png)



Cleo Redux Log

> 10:25:00 [INFO] CLEO Redux 1.0.5 (x86)
10:25:00 [INFO] Copyright (c) 2021-2022, Seemann. Available under the license agreement at https://re.cleo.li/LICENSE.txt
10:25:00 [INFO] Visit re.cleo.li for news and updates.
10:25:00 [INFO] Host identified as Grand Theft Auto: San Andreas (1.0)
10:25:00 [INFO] Image base address 0x400000
10:25:00 [INFO] Found another instance of CLEO. Compiled scripts support is delegated.
10:25:01 [INFO] Registering custom commands
10:25:01 [INFO] Registering command IS_KEY_PRESSED
10:25:01 [INFO] Registering unsafe command READ_MEMORY with required permission mem
10:25:01 [INFO] Registering unsafe command WRITE_MEMORY with required permission mem
10:25:01 [INFO] Registering unsafe command CALL_FUNCTION with required permission mem
10:25:01 [INFO] SDK version 6
10:25:01 [INFO] Loading plugins from E:\STEAM_GAMES\GTA-SanAndreas-v1.0-Retail\CLEO\CLEO_PLUGINS
10:25:01 [INFO] Found plugin dylib.cleo
10:25:02 [INFO] Dylib plugin 1.1
10:25:02 [INFO] Registering unsafe command LOAD_DYNAMIC_LIBRARY with required permission dll
10:25:02 [INFO] Registering unsafe command FREE_DYNAMIC_LIBRARY with required permission dll
10:25:02 [INFO] Registering unsafe command GET_DYNAMIC_LIBRARY_PROCEDURE with required permission dll
10:25:02 [INFO] Loaded plugin dylib.cleo
10:25:02 [INFO] Found plugin Frontend.cleo
10:25:03 [INFO] Initializing Frontend plugin v1.1
10:25:03 [INFO] Loaded plugin Frontend.cleo
10:25:03 [INFO] Found plugin IdeLoader.cleo
10:25:04 [INFO] IDE Loader 1.2
10:25:04 [INFO] Registering a custom loader for glob "*.ide"
10:25:04 [INFO] Loaded plugin IdeLoader.cleo
10:25:04 [INFO] Found plugin ImGuiReduxWin32.cleo
10:25:06 [INFO] Registering command IMGUI_BEGIN_FRAME
10:25:06 [INFO] Registering command IMGUI_END_FRAME
10:25:06 [INFO] Registering command IMGUI_BEGIN
10:25:06 [INFO] Registering command IMGUI_END
10:25:06 [INFO] Registering command IMGUI_SET_WINDOW_POS
10:25:06 [INFO] Registering command IMGUI_SET_WINDOW_SIZE
10:25:06 [INFO] Registering command IMGUI_SET_NEXT_WINDOW_POS
10:25:06 [INFO] Registering command IMGUI_SET_NEXT_WINDOW_SIZE
10:25:06 [INFO] Registering command IMGUI_DUMMY
10:25:06 [INFO] Registering command IMGUI_TEXT
10:25:06 [INFO] Registering command IMGUI_TEXT_CENTERED
10:25:06 [INFO] Registering command IMGUI_TEXT_DISABLED
10:25:06 [INFO] Registering command IMGUI_TEXT_WRAPPED
10:25:06 [INFO] Registering command IMGUI_TEXT_COLORED
10:25:06 [INFO] Registering command IMGUI_BULLET_TEXT
10:25:06 [INFO] Registering command IMGUI_SET_TOOLTIP
10:25:06 [INFO] Registering command IMGUI_BUTTON
10:25:06 [INFO] Registering command IMGUI_IMAGE_BUTTON
10:25:06 [INFO] Registering command IMGUI_INVISIBLE_BUTTON
10:25:06 [INFO] Registering command IMGUI_COLOR_BUTTON
10:25:06 [INFO] Registering command IMGUI_ARROW_BUTTON
10:25:06 [INFO] Registering command IMGUI_CHECKBOX
10:25:06 [INFO] Registering command IMGUI_SAMELINE
10:25:06 [INFO] Registering command IMGUI_NEWLINE
10:25:06 [INFO] Registering command IMGUI_COLUMNS
10:25:06 [INFO] Registering command IMGUI_NEXT_COLUMN
10:25:06 [INFO] Registering command IMGUI_SPACING
10:25:06 [INFO] Registering command IMGUI_SEPARATOR
10:25:06 [INFO] Registering command GET_FRAMERATE
10:25:06 [INFO] Registering command IMGUI_GET_VERSION
10:25:06 [INFO] Registering command IMGUI_GET_PLUGIN_VERSION
10:25:06 [INFO] Registering command IMGUI_SET_CURSOR_VISIBLE
10:25:06 [INFO] Registering command IMGUI_GET_FRAME_HEIGHT
10:25:06 [INFO] Registering command IMGUI_GET_WINDOW_POS
10:25:06 [INFO] Registering command IMGUI_GET_WINDOW_SIZE
10:25:06 [INFO] Registering command IMGUI_CALC_TEXT_SIZE
10:25:06 [INFO] Registering command IMGUI_GET_WINDOW_CONTENT_REGION_WIDTH
10:25:06 [INFO] Registering command IMGUI_BEGIN_MAINMENUBAR
10:25:06 [INFO] Registering command IMGUI_END_MAINMENUBAR
10:25:06 [INFO] Registering command IMGUI_MENU_ITEM
10:25:06 [INFO] Registering command IMGUI_SELECTABLE
10:25:06 [INFO] Registering command IMGUI_BEGIN_CHILD
10:25:06 [INFO] Registering command IMGUI_END_CHILD
10:25:06 [INFO] Registering command IMGUI_PUSH_ITEM_WIDTH
10:25:06 [INFO] Registering command IMGUI_POP_ITEM_WIDTH
10:25:06 [INFO] Registering command IMGUI_COLLAPSING_HEADER
10:25:06 [INFO] Registering command IMGUI_SLIDER_INT
10:25:06 [INFO] Registering command IMGUI_SLIDER_FLOAT
10:25:06 [INFO] Registering command IMGUI_INPUT_INT
10:25:06 [INFO] Registering command IMGUI_INPUT_FLOAT
10:25:06 [INFO] Registering command IMGUI_INPUT_TEXT
10:25:06 [INFO] Registering command IMGUI_RADIO_BUTTON
10:25:06 [INFO] Registering command IMGUI_COLOR_PICKER
10:25:06 [INFO] Registering command IMGUI_IS_ITEM_ACTIVE
10:25:06 [INFO] Registering command IMGUI_IS_ITEM_CLICKED
10:25:06 [INFO] Registering command IMGUI_IS_ITEM_FOCUSED
10:25:06 [INFO] Registering command IMGUI_IS_ITEM_HOVERED
10:25:06 [INFO] Registering command IMGUI_GET_SCALING_SIZE
10:25:06 [INFO] Registering command IMGUI_GET_DISPLAY_SIZE
10:25:06 [INFO] Registering command IMGUI_SET_NEXT_WINDOW_TRANSPARENCY
10:25:06 [INFO] Registering command IMGUI_SET_MESSAGE
10:25:06 [INFO] Registering command IMGUI_BULLET
10:25:06 [INFO] Registering command IMGUI_COMBO
10:25:06 [INFO] Registering command IMGUI_SET_IMAGE_BG_COLOR
10:25:06 [INFO] Registering command IMGUI_SET_IMAGE_TINT_COLOR
10:25:06 [INFO] Registering command IMGUI_LOAD_IMAGE
10:25:06 [INFO] Registering command IMGUI_FREE_IMAGE
10:25:06 [INFO] Registering command IMGUI_PUSH_STYLE_VAR
10:25:06 [INFO] Registering command IMGUI_PUSH_STYLE_VAR2
10:25:06 [INFO] Registering command IMGUI_PUSH_STYLE_COLOR
10:25:06 [INFO] Registering command IMGUI_POP_STYLE_VAR
10:25:06 [INFO] Registering command IMGUI_POP_STYLE_COLOR
10:25:06 [INFO] Registering command IMGUI_TABS
10:25:06 [INFO] Registering command IMGUI_GET_FOREGROUND_DRAWLIST
10:25:06 [INFO] Registering command IMGUI_GET_BACKGROUND_DRAWLIST
10:25:06 [INFO] Registering command IMGUI_GET_WINDOW_DRAWLIST
10:25:06 [INFO] Registering command IMGUI_DRAWLIST_ADD_TEXT
10:25:06 [INFO] Registering command IMGUI_DRAWLIST_ADD_LINE
10:25:06 [INFO] Loaded plugin ImGuiReduxWin32.cleo
10:25:06 [INFO] Found plugin IniFiles.cleo
10:25:06 [INFO] IniFiles plugin 1.2
10:25:06 [INFO] Registering unsafe command READ_INT_FROM_INI_FILE with required permission fs
10:25:06 [INFO] Registering unsafe command WRITE_INT_TO_INI_FILE with required permission fs
10:25:06 [INFO] Registering unsafe command READ_FLOAT_FROM_INI_FILE with required permission fs
10:25:06 [INFO] Registering unsafe command WRITE_FLOAT_TO_INI_FILE with required permission fs
10:25:06 [INFO] Registering unsafe command READ_STRING_FROM_INI_FILE with required permission fs
10:25:06 [INFO] Registering unsafe command WRITE_STRING_TO_INI_FILE with required permission fs
10:25:06 [INFO] Loaded plugin IniFiles.cleo
10:25:06 [INFO] Found plugin Input.cleo
10:25:07 [INFO] Input plugin 1.3
10:25:07 [INFO] Registering command IS_KEY_PRESSED
10:25:07 [INFO] Registering command IS_KEY_DOWN
10:25:07 [INFO] Registering command IS_KEY_UP
10:25:07 [INFO] Registering command GET_LAST_KEY
10:25:07 [INFO] Registering command TEST_CHEAT
10:25:07 [INFO] Registering command HOLD_KEY
10:25:07 [INFO] Registering command RELEASE_KEY
10:25:07 [INFO] Registering command SET_CURSOR_POS
10:25:07 [INFO] Registering command GET_CURSOR_POS
10:25:07 [INFO] Loaded plugin Input.cleo
10:25:07 [INFO] Found plugin MemoryOperations.cleo
10:25:07 [INFO] Init MemoryOperations
10:25:07 [INFO] Registering unsafe command GET_IMAGE_BASE with required permission mem
10:25:07 [INFO] Registering unsafe command FIND_PATTERN with required permission mem
10:25:07 [INFO] Registering unsafe command ALLOC_NEAR with required permission mem
10:25:07 [INFO] Registering unsafe command READ_RELATIVE_OFFSET with required permission mem
10:25:07 [INFO] Registering unsafe command WRITE_RELATIVE_OFFSET with required permission mem
10:25:07 [INFO] Loaded plugin MemoryOperations.cleo
10:25:07 [INFO] Found plugin TextLoader.cleo
10:25:09 [INFO] TXT Loader 1.0
10:25:09 [INFO] Registering a custom loader for glob "*.txt"
10:25:09 [INFO] Registering a custom loader for glob "*.text"
10:25:09 [INFO] Loaded plugin TextLoader.cleo
10:25:09 [INFO] API version 0.296
10:25:09 [WARN] Description of class ColPoint not found
10:25:09 [WARN] Description of class Entity not found
10:25:09 [WARN] Description of class ColPoint not found
10:25:09 [WARN] Description of class Entity not found
10:25:09 [INFO] FXT files successfully loaded
10:25:17 [INFO] [ImGuiRedux] SilentPatch not found. Please install it from here https://gtaforums.com/topic/669045-silentpatch/
10:26:54 [INFO] New event received: "host shut down"
10:26:54 [INFO] Exit

@x87 @user-grinch

**Comment by user-grinch** [comment]
@1234nir That's kinda strange. I tried it on my end, no such issues. What does your modloader installation look like? Can you share screenshots of your game & modloader directory?

**Comment by 1234nir** [comment]
currently i dosent able to use my pc..

How to Reproduce?

1. Create any folder in modloader and move silent patch files to that
2. restart pc & after restart
3. start game (gta_sa.exe) you will get this window

**Comment by 1234nir** [comment]
> @1234nir That's kinda strange. I tried it on my end, no such issues. What does your modloader installation look like? Can you share screenshots of your game & modloader directory?

**Main**
![Screenshot (255)](https://user-images.githubusercontent.com/120308983/208906907-414626ff-5b33-410d-bec2-ee119f014024.png)

**Scripts**
![Screenshot (256)](https://user-images.githubusercontent.com/120308983/208906923-f7f3c77a-4b0e-4f03-bcdb-d1e8ee8f2944.png)

**Modloader**
![Screenshot (257)](https://user-images.githubusercontent.com/120308983/208906927-5d4f17ab-f6ac-4d7c-8e45-1af0242d2abe.png)

**Comment by 1234nir** [comment]
@user-grinch ?

**Comment by user-grinch** [comment]
I don't really see anything wrong here. Hit me up on discord when you got some time. 
![image](https://user-images.githubusercontent.com/29150216/209197233-f85165a9-29fa-4870-be3c-1f4600619742.png)

**Comment by user-grinch** [comment]
@1234nir Can you try with [this](https://github.com/user-grinch/ImGuiRedux/suites/10223242127/artifacts/500973334)?

**Comment by 1234nir** [comment]
> @1234nir Can you try with [this](https://github.com/user-grinch/ImGuiRedux/suites/10223242127/artifacts/500973334)?

I will test & send feedback soon as possible.

**Comment by 1234nir** [comment]
> @1234nir Can you try with [this](https://github.com/user-grinch/ImGuiRedux/suites/10223242127/artifacts/500973334)?

@user-grinch @x87 


i just try again and again, but not get that popup any single time..

**So, I Think "The Issue Has Been Resolve"**

Keep it Up

**Comment by 1234nir** [comment]
Hey @x87
You can Close this Issue, as This Issue Has Been Fixed.

**Comment by 1234nir** [comment]
Hey @x87
You can Close This, as This Issue Has Been Fixed.
