### ISSUE TITLE
For Installer (UAL Filename)

### ISSUE THREAD

**Issue by 1234nir** [cleolibrary/CLEO-Redux#84]
Currently, Installer install **Ultimate Asi Loader** as **VorbisFile.dll** ..... But in **Gta-vice-city/GTA-III vorbisFile.dll not supported,** these games support dinput8.dll

Before Install CLEO-Redux, Installer Check Is SA/VC/III... So you can add a simple code to install right filename of ASI Loader

**IsSA = Install VorbisFile.dll
IsVC = Install dinput8.dll
IsIII = Install dinput8.dll**

**Comment by x87** [comment]
You don't need ASI Loader in GTA III and Vice City. These games use MSS library that provides support for ASI plugins out of the box.

**Comment by 1234nir** [comment]
There are many mods need separate ASI Loader for VC

One of the Popular [SkyGFX](https://gtaforums.com/topic/750681-skygfx-ps2-xbox-and-mobile-graphics-for-pc/) 

![IMG_20230107_225356](https://user-images.githubusercontent.com/120308983/211162978-597b1a97-f3a0-4c53-98fe-3d9497ac9286.jpg)

**Comment by x87** [comment]
If you need ASI loader for other mods, you can install it separately. I don't see why it is a CLEO Redux problem.

**Comment by 1234nir** [comment]
> If you need ASI loader for other mods, you can install it separately. I don't see why it is a CLEO Redux problem.

yeh

**Comment by 1234nir** [comment]
For Your Information,
@user-grinch fix this problem in [CheatMenu Installer](https://github.com/user-grinch/Cheat-Menu) (Which is based on CLEO Redux Installer)

CheatMenu Installer InnoSetup Script https://github.com/user-grinch/Cheat-Menu/blob/master/installer/installer.iss

**Comment by user-grinch** [comment]
"I fixed it" since CheatMenu requires Ultimate ASI Loader to function properly. I agree with Seeman here. The goal of CLEORedix installer to make CLEORedix loadable, other mods shouldn't be a concern.

**Comment by 1234nir** [comment]
It's OK, came to my mind that's why I said

**Comment by 1234nir** [comment]
Hey, @x87 

You have done it this in [CLEO Redux v1.0.6](https://github.com/cleolibrary/CLEO-Redux/releases/tag/1.0.6l), So you can close this.
