### ISSUE TITLE
[RGL] 1.1.2 Crashes San Andreas Definitive Edition when loading a Save.

### ISSUE THREAD

**Issue by DreamsInAutumn** [cleolibrary/CLEO-Redux#90]
![2023-02-18](https://user-images.githubusercontent.com/99279454/219901562-21970e8a-4e4c-49aa-b783-aebae12a2186.png)

All previous Cleo files and loaders removed from the Game Directory, APPDATA directory, and no plugins/JS installed.
Game loads and plays with Cleo removed.

**Comment by x87** [comment]
show cleo_redux.log and UE crash log from \Documents\Rockstar Games\GTA San Andreas Definitive Edition\Crashes (CrashContext.runtime-xml)

**Comment by DreamsInAutumn** [comment]
[cleo_redux.log](https://github.com/cleolibrary/CLEO-Redux/files/10775305/cleo_redux.log)
[CrashContext.runtime-xml.TXT](https://github.com/cleolibrary/CLEO-Redux/files/10775310/CrashContext.runtime-xml.TXT)

**Comment by x87** [comment]
Is this Steam release or Epic?

**Comment by DreamsInAutumn** [comment]
Neither Steam or Epic, purchased from Rockstar at launch.

**Comment by x87** [comment]
Can you find me on Discord? https://discord.gg/d5dZSfgBZr

**Comment by DreamsInAutumn** [comment]
I @you there.

**Comment by x87** [comment]
I shared an updated version on Discord with RGL support. I'd appreciate if you or anyone else could give it a shot and report back if it is working fine on latest Trilogy in Rockstar Game Launcher

**Comment by x87** [comment]
1.1.3 released https://github.com/cleolibrary/CLEO-Redux/releases/tag/1.1.3
