### ISSUE TITLE
Text operations bug in 1.2.1

### ISSUE THREAD

**Issue by strejda603** [cleolibrary/CLEO-Redux#99]
Hello @x87,

I have noticed, that in 1.2.1 any "Text" operation (*Text.PrintBig, Text.PrintHelp, Text.PrintNow...*) from "CLEO_TEXT" (from **.fxt** files) doesn't work - maybe there is some problem with reading .fxt files...

If I use some text defined in main **.gxt** file, then it works.. Could you try to fix it? It worked good in 1.2.0

Thank you!

**Comment by x87** [comment]
Can you provide more details? What game? Show code

**Comment by x87** [comment]
I cannot reproduce this issue. I took fresh GTA VC from steam, downgraded to 1.0, installed VC.CLEO 2.0.0.6, CLEO Redux 1.2.1 and SilentPatch.

This is my test script:

```
Text.PrintNow("TEST", 5000, 1);
```

this is my FXT (CLEO_TEXT\1.fxt)

```
TEST This is a test message
```

I can see "This is a test message" when I run the game.


Try disabling ALL scripts and FXT files, and test with a single JS script & single FXT file. Would it work?

**Comment by x87** [comment]
Also question: does it work with this build https://github.com/cleolibrary/CLEO-Redux/issues/98#issuecomment-1676172539 ?

**Comment by strejda603** [comment]
Honestly, I have no clue, what is wrong... It used to work, I did nothing (just played the game, and updated CLEO Redux from 1.2.0 to 1.2.1), and it just stopped working.. I tried to disable all scripts, modloader, etc. and left just VC.CLEO 2.0.0.6, CLEO Redux 1.2.1 and SilentPatch on, even start new game: no luck...

> Also question: does it work with this build [#98 (comment)](https://github.com/cleolibrary/CLEO-Redux/issues/98#issuecomment-1676172539) ?

No, it doesn't. And now, even v1.2.0 doesn't work..

It's strange, everything other work just fine, and only displaying text from FXT files doesn't...

I'm trying to combine [Ultra Mod](https://www.moddb.com/mods/gta-vice-city-ultra-edition) with [Extended Features Mod](https://www.moddb.com/mods/grand-theft-auto-vice-city-extended-features). [Here](https://mega.nz/file/toVzCZob#QyEv4IvzXXjIycrCKV8dTU4HOkViKBXfMrshz_ngQ7s) is my whole Vice City folder (and a [save file](https://mega.nz/file/pwVnBRLC#Eo3dRLMtbBZ30uBXWhjAeCbJ2buNwDb_iveMtUkiWIA)). If you have some time, could you please try to look at it? Maybe you'll notice something I won't..

Thank you very much!

**Comment by x87** [comment]
Delete ZMenuVC or make it so its ASI file loads BEFORE cleo_redux.asi

**Comment by strejda603** [comment]
Thank you for your help! I renamed "ZMenuVC.asi" to "1ZMenuVC.asi" to load before CLEO Redux, and it works great.
